import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { inter, notoSansJP } from '@/lib/font';
import '@/app/globals.css';
import Header from '@/components/component/Header';

type Props = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: 'udemy-nextjs15-newhooks-with-sns-dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <ClerkProvider>
      <html lang="ja" className="h-full">
        <body
          className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans flex flex-col h-full`}
        >
          <Header />
          <main className="flex-1">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
