import type { Metadata } from 'next';
import { Inter, Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import Header from '@/components/component/Header';

type Props = Readonly<{
  children: React.ReactNode;
}>;

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'udemy-nextjs15-newhooks-with-sns-dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ja" className="h-full">
      <body className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans flex flex-col h-full`}>
        <Header />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
