import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { inter, notoSansJP } from '@/lib/font';
import '@/app/globals.css';
import Header from '@/components/component/Header';

type Props = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: 'udemy-nextjs15-newhooks-with-sns-dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <ClerkProvider>
      <html lang="ja" className="h-full">
        <body className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans`}>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1 flex flex-col overflow-hidden">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
